### ISSUE TITLE
Autogenerating primary key IDs in Ecto creating v4 UUIDs when I define v6

### ISSUE THREAD

**Issue by ryanwinchester** [sevenshores/elixir-uuid-utils#15]
```
  1) test Repo autogenerates proper UUID (UUID.Ecto.TypeTest)
     test/uuid/ecto/type_test.exs:162
     ** (Ecto.ChangeError) value `"1eb13723-da2d-6cc6-87fc-116a4aa5c86d"` for `UUID.TestSchema.foo_bar_id`
 in `insert` does not match type UUID.TestUUID6
     code: |> UUID.TestRepo.insert()
     stacktrace:
       (ecto 3.5.2) lib/ecto/repo/schema.ex:889: Ecto.Repo.Schema.dump_field!/6
       (ecto 3.5.2) lib/ecto/repo/schema.ex:898: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
       (stdlib 3.13) maps.erl:233: :maps.fold_1/3
       (ecto 3.5.2) lib/ecto/repo/schema.ex:896: Ecto.Repo.Schema.dump_fields!/5
       (ecto 3.5.2) lib/ecto/repo/schema.ex:829: Ecto.Repo.Schema.dump_changes!/6
       (ecto 3.5.2) lib/ecto/repo/schema.ex:255: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       test/uuid/ecto/type_test.exs:166: (test)
```

**Comment by ryanwinchester** [comment]
The issue was literally

```diff
-   @impl Ecto.Type
-   def type, do: :binary_id
+   @impl Ecto.Type
+   def type, do: :uuid
```
